server:
  port: 8011

management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  profiles:
    active: dev
  application:
    name: member-service

# JWT 설정
jwt:
  jwtSecret: vdsf98WEDj2923ksdFWEj239wDEfw293DFWWeijrFwEDjfFWE123123123123123
  jwtExpirationMs: 3600000 # 1시간 (밀리초 단위)
  jwtRefreshExpirationMs: 86400000 # 24시간 (밀리초 단위)
  refreshTokenDurationMinutes: 1440 # 24시간 (분 단위)