spring:
  kafka:
    bootstrap-servers: kafka:9092,kafka-2:9093,kafka-3:9094
    consumer:
      group-id: bookquery
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: "*"
        spring.json.type.mapping: com.example.bookservice.domain.event.BookCreatedMessage:com.example.bookqueryservice.application.message.BookCreatedMessage
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka
