server:
  port: 9001

spring:
  application:
    name: apigateway
  cloud:
    gateway:
      routes:
        - id: member-service
          uri: lb://member-service
          predicates:
            - Path=/api/member/**
        - id: book-service
          uri: lb://book-service
          predicates:
            - Path=/api/book/**
      default-filters:
        - name : GlobalAuthFilter
  session:
    redis:
      namespace: your-app-name
  
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"
