server:
  port: 9001

spring:
  application:
    name: apigateway
  cloud:
    gateway:
      routes:
        - id: member-service
          uri: lb://member-service
          predicates:
            - Path=/api/member/**
          filters:
            - name: JwtAuthFilter
        - id: book-service
          uri: lb://book-service
          predicates:
            - Path=/api/book/**
          filters:
            - name: JwtAuthFilter
        - id: book-query-service
          uri: lb://book-query-service
          predicates:
            - Path=/api/book-query/**
  #     default-filters:
  #       - name : GlobalAuthFilter
  session:
    redis:
      namespace: your-app-name
  
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka
      #http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"
jwt:
  secret: vdsf98WEDj2923ksdFWEj239wDEfw293DFWWeijrFwEDjfFWE123123123123123